import json
import sys
import uuid
from pathlib import Path
from typing import Any

from fastapi import APIRouter, File, HTTPException, Query, UploadFile
from fastapi.responses import FileResponse
from pydantic import BaseModel

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
OUTPUT_DIR = PROJECT_ROOT / "output"
REPORTS_DIR = PROJECT_ROOT / "reports"

OUTPUT_DIR.mkdir(exist_ok=True)
REPORTS_DIR.mkdir(exist_ok=True)

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from performance_monitor import top_processes  # noqa: E402
from file_organizer import organize_files  # noqa: E402
from log_analyzer import analyze_log_file  # noqa: E402
from data_validator import process_csv  # noqa: E402
from system_health_checker import (  # noqa: E402
    get_system_health,
    determine_status,
)
from report_generator import generate_report  # noqa: E402
from api_client import get_public_ip, get_repo_status  # noqa: E402


router = APIRouter(
    prefix="/api",
    tags=["Tools"],
)


# ============================================================
# HELPERS
# ============================================================

def make_json_safe(value: Any):
    """
    Convert values returned by Python scripts into JSON-safe data.
    """
    if value is None:
        return None

    if isinstance(value, (str, int, float, bool)):
        return value

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, dict):
        return {
            str(key): make_json_safe(val)
            for key, val in value.items()
        }

    if isinstance(value, (list, tuple, set)):
        return [
            make_json_safe(item)
            for item in value
        ]

    return str(value)


def normalize_invalid_records(records):
    """
    Convert invalid CSV validation results into a consistent
    frontend-friendly structure.

    The data validator returns invalid records as:

        (
            record,
            ["Missing 'email'"]
        )

    The API returns them as:

        {
            "record": {...},
            "problems": ["Missing 'email'"]
        }
    """
    normalized = []

    for item in records:

        if isinstance(item, dict):
            record = item.get(
                "record",
                {},
            )

            problems = item.get(
                "problems",
                [],
            )

        elif isinstance(item, (tuple, list)) and len(item) >= 2:
            record = item[0]
            problems = item[1]

        else:
            record = {}
            problems = [str(item)]

        normalized.append(
            {
                "record": make_json_safe(record),
                "problems": make_json_safe(problems),
            }
        )

    return normalized


def find_generated_file(
    result: Any,
    directory: Path,
    extensions: tuple[str, ...] = (),
):
    """
    Try to determine which file was generated by a script.
    """

    if isinstance(result, (str, Path)):
        candidate = Path(result)

        if not candidate.is_absolute():
            candidate = PROJECT_ROOT / candidate

        if candidate.exists() and candidate.is_file():
            return candidate

    if isinstance(result, dict):
        for key in (
            "output_path",
            "path",
            "file",
            "filename",
        ):
            value = result.get(key)

            if value:
                candidate = Path(str(value))

                if not candidate.is_absolute():
                    candidate = PROJECT_ROOT / candidate

                if candidate.exists() and candidate.is_file():
                    return candidate

    files = [
        path
        for path in directory.iterdir()
        if path.is_file()
        and (
            not extensions
            or path.suffix.lower() in extensions
        )
    ]

    if not files:
        return None

    return max(
        files,
        key=lambda path: path.stat().st_mtime,
    )


# ============================================================
# PERFORMANCE
# ============================================================

@router.get("/performance")
def performance(
    sort_by: str = Query(
        "cpu",
        pattern="^(cpu|memory)$",
    ),
    limit: int = Query(
        10,
        ge=1,
        le=50,
    ),
):
    try:
        processes = top_processes(
            limit=limit,
            sort_by=sort_by,
        )

        return {
            "sort_by": sort_by,
            "limit": limit,
            "processes": make_json_safe(
                processes
            ),
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "Unable to collect performance data."
                ),
                "error": str(exc),
            },
        )


# ============================================================
# FILE ORGANIZER
# ============================================================

class FileOrganizerRequest(BaseModel):
    folder_path: str


@router.post("/file-organizer")
def file_organizer(
    request: FileOrganizerRequest,
):
    folder = Path(
        request.folder_path
    ).expanduser()

    if not folder.exists():
        raise HTTPException(
            status_code=400,
            detail={
                "message": (
                    "The selected folder does not exist."
                ),
                "folder": str(folder),
                "reason": (
                    "The path could not be found "
                    "on this computer."
                ),
            },
        )

    if not folder.is_dir():
        raise HTTPException(
            status_code=400,
            detail={
                "message": (
                    "The selected path is not a folder."
                ),
                "folder": str(folder),
                "reason": (
                    "Please provide a directory "
                    "rather than a file."
                ),
            },
        )

    try:
        result = organize_files(
            str(folder)
        )

        if isinstance(result, dict):
            return {
                "success": (
                    len(
                        result.get(
                            "errors",
                            [],
                        )
                    )
                    == 0
                ),
                "folder": str(folder),
                "moved": make_json_safe(
                    result.get(
                        "moved",
                        [],
                    )
                ),
                "skipped": make_json_safe(
                    result.get(
                        "skipped",
                        [],
                    )
                ),
                "errors": make_json_safe(
                    result.get(
                        "errors",
                        [],
                    )
                ),
                "summary": {
                    "moved": len(
                        result.get(
                            "moved",
                            [],
                        )
                    ),
                    "skipped": len(
                        result.get(
                            "skipped",
                            [],
                        )
                    ),
                    "errors": len(
                        result.get(
                            "errors",
                            [],
                        )
                    ),
                },
            }

        return {
            "success": True,
            "folder": str(folder),
            "message": (
                "File organization completed "
                "successfully."
            ),
            "result": make_json_safe(
                result
            ),
            "summary": {
                "moved": "Completed",
                "skipped": 0,
                "errors": 0,
            },
        }

    except PermissionError as exc:
        raise HTTPException(
            status_code=403,
            detail={
                "message": (
                    "Permission denied while "
                    "organizing files."
                ),
                "folder": str(folder),
                "reason": str(exc),
                "suggestion": (
                    "Make sure the folder is not "
                    "protected and that you have "
                    "permission to move files."
                ),
            },
        )

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=404,
            detail={
                "message": (
                    "A file or folder could not "
                    "be found."
                ),
                "folder": str(folder),
                "reason": str(exc),
            },
        )

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "File organization failed."
                ),
                "folder": str(folder),
                "error_type": type(exc).__name__,
                "reason": str(exc),
            },
        )


# ============================================================
# LOG ANALYZER
# ============================================================

@router.post("/log-analyzer")
async def log_analyzer(
    file: UploadFile = File(...),
):
    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="No log file was selected.",
        )

    temp_dir = OUTPUT_DIR / "uploads"
    temp_dir.mkdir(
        exist_ok=True
    )

    temp_file = (
        temp_dir
        / f"{uuid.uuid4()}_{file.filename}"
    )

    try:
        content = await file.read()

        temp_file.write_bytes(
            content
        )

        (
            info_count,
            warning_count,
            error_count,
            errors,
        ) = analyze_log_file(
            str(temp_file)
        )

        return {
            "filename": file.filename,
            "info_count": info_count,
            "warning_count": warning_count,
            "error_count": error_count,
            "errors": make_json_safe(
                errors
            ),
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "Log analysis failed."
                ),
                "filename": file.filename,
                "error_type": type(exc).__name__,
                "reason": str(exc),
            },
        )

    finally:
        if temp_file.exists():
            temp_file.unlink()


# ============================================================
# CSV VALIDATOR
# ============================================================

@router.post("/csv-validator")
async def csv_validator(
    file: UploadFile = File(...),
):
    if not file.filename:
        raise HTTPException(
            status_code=400,
            detail="No CSV file was selected.",
        )

    if not file.filename.lower().endswith(
        ".csv"
    ):
        raise HTTPException(
            status_code=400,
            detail={
                "message": "Invalid file type.",
                "reason": (
                    "Please upload a CSV file."
                ),
            },
        )

    upload_dir = (
        OUTPUT_DIR / "csv_uploads"
    )

    upload_dir.mkdir(
        exist_ok=True
    )

    cleaned_dir = (
        OUTPUT_DIR / "cleaned_csv"
    )

    cleaned_dir.mkdir(
        exist_ok=True
    )

    unique_id = uuid.uuid4().hex

    input_path = (
        upload_dir
        / f"{unique_id}_{file.filename}"
    )

    cleaned_filename = (
        f"cleaned_"
        f"{Path(file.filename).stem}_"
        f"{unique_id[:8]}.csv"
    )

    output_path = (
        cleaned_dir
        / cleaned_filename
    )

    try:
        # ----------------------------------------------------
        # Save uploaded CSV
        # ----------------------------------------------------

        content = await file.read()

        input_path.write_bytes(
            content
        )

        # ----------------------------------------------------
        # Run the existing Python validator
        # ----------------------------------------------------

        result = process_csv(
            str(input_path),
            output_path=str(output_path),
        )

        # ----------------------------------------------------
        # Normalise validator result
        # ----------------------------------------------------

        clean_records = []
        invalid_records = []
        duplicate_records = []

        returned_output_path = output_path

        if isinstance(result, tuple):

            if len(result) >= 1:
                clean_records = result[0]

            if len(result) >= 2:
                invalid_records = result[1]

            if len(result) >= 3:
                duplicate_records = result[2]

            if (
                len(result) >= 4
                and result[3]
            ):
                returned_output_path = Path(
                    str(result[3])
                )

                if not returned_output_path.is_absolute():
                    returned_output_path = (
                        PROJECT_ROOT
                        / returned_output_path
                    )

        elif isinstance(result, dict):

            clean_records = result.get(
                "clean",
                result.get(
                    "clean_records",
                    [],
                ),
            )

            invalid_records = result.get(
                "invalid",
                result.get(
                    "invalid_records",
                    [],
                ),
            )

            duplicate_records = result.get(
                "duplicates",
                result.get(
                    "duplicate_records",
                    [],
                ),
            )

            returned_output_path = Path(
                str(
                    result.get(
                        "output_path",
                        output_path,
                    )
                )
            )

            if not returned_output_path.is_absolute():
                returned_output_path = (
                    PROJECT_ROOT
                    / returned_output_path
                )

        # ----------------------------------------------------
        # Guarantee lists
        # ----------------------------------------------------

        if not isinstance(
            clean_records,
            list,
        ):
            clean_records = list(
                clean_records or []
            )

        if not isinstance(
            invalid_records,
            list,
        ):
            invalid_records = list(
                invalid_records or []
            )

        if not isinstance(
            duplicate_records,
            list,
        ):
            duplicate_records = list(
                duplicate_records or []
            )

        # ----------------------------------------------------
        # Make sure cleaned CSV exists
        # ----------------------------------------------------

        if not returned_output_path.exists():

            if output_path.exists():
                returned_output_path = (
                    output_path
                )

            else:
                raise FileNotFoundError(
                    "The CSV validator completed "
                    "but did not create the "
                    "cleaned CSV file."
                )

        # ----------------------------------------------------
        # Copy cleaned CSV into controlled
        # download directory
        # ----------------------------------------------------

        if (
            returned_output_path.resolve()
            != output_path.resolve()
        ):
            output_path.write_bytes(
                returned_output_path.read_bytes()
            )

        # ----------------------------------------------------
        # Download URL
        # ----------------------------------------------------

        download_url = (
            f"/api/csv-validator/download/"
            f"{output_path.name}"
        )

        # ----------------------------------------------------
        # Normalize invalid records
        # ----------------------------------------------------

        invalid_response = (
            normalize_invalid_records(
                invalid_records
            )
        )

        # ----------------------------------------------------
        # Counts
        # ----------------------------------------------------

        clean_count = len(
            clean_records
        )

        invalid_count = len(
            invalid_records
        )

        duplicate_count = len(
            duplicate_records
        )

        # ----------------------------------------------------
        # API RESPONSE
        # ----------------------------------------------------

        return {
            "success": True,
            "filename": file.filename,

            # Full record arrays
            "clean": make_json_safe(
                clean_records
            ),

            "invalid": invalid_response,

            "duplicates": make_json_safe(
                duplicate_records
            ),

            # Numeric counts
            "clean_records": clean_count,
            "invalid_records": invalid_count,
            "duplicate_records": duplicate_count,

            # Summary
            "counts": {
                "clean": clean_count,
                "invalid": invalid_count,
                "duplicates": duplicate_count,
                "total": (
                    clean_count
                    + invalid_count
                    + duplicate_count
                ),
            },

            # Cleaned file
            "cleaned_file": (
                output_path.name
            ),

            "output_path": str(
                output_path
            ),

            # Download
            "download_url": download_url,
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "CSV validation failed."
                ),
                "filename": file.filename,
                "error_type": type(exc).__name__,
                "reason": str(exc),
            },
        )

    finally:
        if input_path.exists():
            input_path.unlink()


# ============================================================
# CSV DOWNLOAD
# ============================================================

@router.get(
    "/csv-validator/download/{filename}"
)
def download_cleaned_csv(
    filename: str,
):
    safe_name = Path(filename).name

    if safe_name != filename:
        raise HTTPException(
            status_code=400,
            detail="Invalid filename.",
        )

    file_path = (
        OUTPUT_DIR
        / "cleaned_csv"
        / safe_name
    )

    if not file_path.exists():
        raise HTTPException(
            status_code=404,
            detail={
                "message": (
                    "Cleaned CSV file not found."
                ),
                "filename": filename,
            },
        )

    return FileResponse(
        path=file_path,
        media_type="text/csv",
        filename=safe_name,
    )


# ============================================================
# HEALTH REPORTS
# ============================================================

@router.post("/reports/health")
def health_report(
    output_format: str = Query(
        "text",
        pattern="^(json|csv|html|text)$",
    ),
):
    try:
        health = get_system_health()

        statuses = {
            "cpu": determine_status(
                health["cpu_usage"]
            ),
            "memory": determine_status(
                health["memory_usage"]
            ),
            "disk": determine_status(
                health["disk_usage"]
            ),
        }

        result = generate_report(
            health,
            statuses,
            output_format=output_format,
        )

        report_file = find_generated_file(
            result,
            REPORTS_DIR,
            extensions=(
                ".json",
                ".csv",
                ".html",
                ".txt",
            ),
        )

        if report_file is None:
            raise FileNotFoundError(
                "The report generator did not "
                "create a report file."
            )

        return {
            "success": True,
            "format": output_format,
            "filename": report_file.name,
            "path": str(report_file),
            "download_url": (
                f"/api/reports/download/"
                f"{report_file.name}"
            ),
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "Report generation failed."
                ),
                "format": output_format,
                "error_type": type(exc).__name__,
                "reason": str(exc),
            },
        )


# ============================================================
# REPORT DOWNLOAD
# ============================================================

@router.get(
    "/reports/download/{filename}"
)
def download_report(
    filename: str,
):
    safe_name = Path(filename).name

    if safe_name != filename:
        raise HTTPException(
            status_code=400,
            detail="Invalid report filename.",
        )

    file_path = (
        REPORTS_DIR
        / safe_name
    )

    if not file_path.exists():
        raise HTTPException(
            status_code=404,
            detail={
                "message": (
                    "Report file not found."
                ),
                "filename": filename,
            },
        )

    media_types = {
        ".json": "application/json",
        ".csv": "text/csv",
        ".html": "text/html",
        ".txt": "text/plain",
    }

    media_type = media_types.get(
        file_path.suffix.lower(),
        "application/octet-stream",
    )

    return FileResponse(
        path=file_path,
        media_type=media_type,
        filename=file_path.name,
    )


# ============================================================
# PUBLIC IP
# ============================================================

@router.get("/public-ip")
def public_ip():
    try:
        return {
            "ip": get_public_ip(),
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "Unable to retrieve public IP."
                ),
                "error": str(exc),
            },
        )


# ============================================================
# GITHUB
# ============================================================

@router.get("/github")
def github(
    owner: str = "NtandoBadla",
    repo: str = "python-utilities-pack",
):
    try:
        return make_json_safe(
            get_repo_status(
                owner,
                repo,
            )
        )

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "Unable to retrieve GitHub "
                    "repository status."
                ),
                "owner": owner,
                "repo": repo,
                "error": str(exc),
            },
        )


# ============================================================
# FULL SCAN
# ============================================================

@router.get("/full-scan")
def full_scan():
    try:
        health = get_system_health()

        statuses = {
            "cpu": determine_status(
                health["cpu_usage"]
            ),
            "memory": determine_status(
                health["memory_usage"]
            ),
            "disk": determine_status(
                health["disk_usage"]
            ),
        }

        processes = top_processes(
            limit=5,
            sort_by="cpu",
        )

        return {
            "health": {
                "hostname": health["hostname"],
                "operating_system": (
                    health["operating_system"]
                ),
                "os_version": (
                    health["os_version"]
                ),
                "cpu": {
                    "usage": health["cpu_usage"],
                    "status": statuses["cpu"],
                },
                "memory": {
                    "usage": health["memory_usage"],
                    "status": statuses["memory"],
                },
                "disk": {
                    "usage": health["disk_usage"],
                    "status": statuses["disk"],
                },
            },
            "top_processes": make_json_safe(
                processes
            ),
        }

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail={
                "message": (
                    "Full system scan failed."
                ),
                "error_type": type(exc).__name__,
                "reason": str(exc),
            },
        )